config/routes.rb
Rails.application.routes.draw do

	root "questions#index"

  devise_for :users, controllers: {
  	sessions: "users/sessions"
  }

  resources :questions do
  	resources :answers 
  end

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "terms", to: "pages#terms"
  
end

app/models/question.rb
class Question < ApplicationRecord
	extend FriendlyId
	has_many :answers
	validates :title, presence: true, length: { maximum: 150 }
	validates :body, presence: true, length: { in: 50..1500 }

	friendly_id :title, use: [:slugged, :history]

	def should_generate_new_friendly_id?
		!has_friendly_id_slug? || title_changed?
	end

	def has_friendly_id_slug?
		slugs.where(slug: slug).exists?
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  
  def index
    @questions = Question.order("created_at DESC")
    @meta_title = meta_title("Nyeste Spørgsmål")
    @meta_description = "Spørg gratis og anonymt advokater og andre juridiske eksperter om råd og vejledning"
  end

  def show
    @answer = Answer.new
    @meta_title = meta_title(@question.title)
    @meta_description = @question.body[0..160]

    respond_with_question_or_redirect
  end

  def new
    @question = Question.new
    @meta_title = meta_title("Stil Spørgsmål")
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Dit spørgsmål er nu oprettet.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Spørgsmålet er slettet.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body)
    end

    def respond_with_question_or_redirect
      if request.path != question_path(@question)
        return redirect_to @question, status: :moved_permanently
      else
        return respond_with @question
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<section class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(question, data: { behavior: "autosave" }, html: { class: "form-horizontal" } ) do |f| %>

      <!-- stupid error box - to be refactored out -->
        <% if question.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
            <% question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>


        <div class="form-group">
          <%= f.label :title, "Overskrift:" %>
          <%= f.text_field :title, placeholder: "Opsummer dit spørgsmål", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :body, "Dit spørgsmål:" %>
          <%= f.text_area :body, placeholder: "Beskriv dit spørgsmål...", class: "form-control", rows: "5" %>
        </div>

        <div class="form-group">
          <%= f.submit "Gem", class: "btn btn-default" %>
        </div>      
      </div>
    <% end %>
  </div>
</section>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1 class="text-center">Nyeste Spørgsmål</h1>

<table class="table table-responsive table-hover">

  <% @questions.each do |question| %>
    <tr>
    	<td><span class="badge"><%= "#{question.answers.size}" %></span></td>
      <td><%= link_to question.title, question, class: "question-index" %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Stil et spørgsmål', new_question_path, class: "btn btn-success btn-lg btn-block" %>

app/views/questions/new.html.erb
<h1 class="text-center">Nyt Spørgsmål</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<section>
  <h1>
  	<%= @question.title %>
  </h1>
	

<hr>

<section class="row">
	<article class="question col-md-9">
	  <%= simple_format @question.body %>
	</article>

	<aside class="col-md-3">
		<%= creation_time(@question) %>
	</aside>
</section>

<hr>

<section class="answers">
	<h2>
		<%= @question.answers.count %> svar
	</h2>

	<%= render @question.answers %>
</section>

<!-- if user is logged in show answer form, 
			otherwise show ask for a log in -->

<% if user_signed_in? %>

	<!--  answer form -->
	<section id="submit-answer">
		<h2>
			Dit svar:
		</h2>
		<%= form_for [@question, @answer], html: { class: "form-horizontal col-sm-8" } do |f| %>
			
			<div class="form-group">
				<%= f.text_area :body, placeholder: "Skriv dit svar her...", class: "form-control", rows: "4" %>
			</div>

			<div class="form-group">
				<%= f.submit "Svar", class: "btn btn-primary" %>
			</div>
		
		<% end %>
	</section> 

<% else %>

	<section class="form-group form-inline">
	<h3>
		Log ind for at svare
	</h3>
	
	<%= form_for(:user, :url => session_path(:user)) do |f| %>
	  <%= f.text_field :email, placeholder: "E-mail", class: "form-control" %>
	  <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
	  <%= f.submit 'Log ind' %>
	  <%= link_to "Glemt password?", new_password_path(:user) %>
	<% end %>

	</section>
<% end %>