config/routes.rb
Rails.application.routes.draw do

	root "questions#index"

  devise_for :users, controllers: {
  	sessions: "users/sessions"
  }

  resources :questions do
  	resources :answers 
  end

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "terms", to: "pages#terms"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @meta_title ? @meta_title : ApplicationController::BRAND_NAME %></title>

    <% if @meta_description.present? %>
    	<meta name="decsription" content="<%= @meta_description %>">
    <% end %>
    
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="odW1wfgI-I9hnBxnNRUmawBM1bT3bFH7f2eVKtL3WFY" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	  <!-- collapsible navbar -->

	  <%= render "shared/navbar" %>
	  
     <!-- main page content -->


	  <div class="container">
	  	<section class="row">
	  		<div class="col-md-8 col-md-offset-2">
	  			<%= render "shared/flash_messages" %>
	    		<%= yield %>
	    	</div>
	    </section>
	  </div>

	  <footer class="footer navbar-fixed-bottom">
      <div class="container">
    		<ul class="col-md-offset-2 list-inline">
          <li><%= link_to "Kontakt", contact_path, class: "footer-link" %></li>
          <li><%= link_to "Vilkår", terms_path, class: "footer-link" %></li>
          <li><%= link_to "Om SubModo", about_path, class: "footer-link" %></li>
        </ul>
      </div>
		</footer>


  </body>
</html>